2 fearture searchrank
Leets-Official/Commitato-BE pull request #12
Opened 2024-07-20 14:45 UTC by 1winhyun

## 📌 요약

-사용자 검색 기능과 경험치에 따른 랭킹 기능 구현

## 📝 상세 내용

- 깃허브에서 받아온 커밋기록을 이용하여 사용자별 경험치를 계산 및 경험치에 따른 티어 구분. 
- 검색 기능: 특정 이용자의 깃허브 아이디를 검색할 경우, 해당 사용자의 이름, 경험치, 티어가 보이도록 구현
- 랭킹 기능: 경험치가 높은 사용자순으로 나열해서 보여줌.
![image](https://github.com/user-attachments/assets/ef56cb40-a933-4d3c-b2dd-48c5f17614d3)

## 🗣️ 질문 및 이외 사항

- 검색 기능과 랭킹 기본적인 로직은 잘 작동하는 것 같습니다. 그런데 경험치와 Tier를 계산하고 정하는 ExpService 로직이 제대로 작동되는게 맞는지 확실하지가 않습니다. 확인 한번 해주시면 정말정말 감사하겠습니다..
- 최선을 다했지만 정말정말 많이 부족할 것 같습니다.... 리뷰 진짜 시원하게 어마어마하게 많이 달아주시면 감사하겠습니다.

## ☑️ 이슈 번호

- close #2

2024-07-20 16:36 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    private boolean isCalculated;//경험치 계산 여부를 나타낸다.
해당 객체가 수정될 시 `false`로 변경되어야 하는 추가 로직이 필요할 것 같습니다. 데이터를 호출하고 같은 날에 커밋을 하면 해당 커밋에 대한 경험치 지급은 누락이 되는 현상이 발생합니다.

2024-07-20 16:44 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
>  }
해당 메서드명은 값을 변경한 의도를 파악하기 힘듭니다. `updateCalculatedStatus `와 같이 변경한 의도를 알 수 있는 메서드 명을 사용해 주시기 바랍니다.

2024-07-20 16:51 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        commits.sort(Comparator.comparing(Commit::getCommitDate));//오름차순으로 정렬
JPA에는 지정한 칼럼을 기준으로 정렬해서 리턴해주는 메서드가 존재합니다. 따라서 아래와 같은 메서드를 `CommitRepository`에 구현한다면 2개의 코드와 같은 기능을 할 겁니다.
```java
List<Commit> findAllByUserOrderByCommitDateAsc(User user);
```

2024-07-20 16:55 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            totalExp+=1+bonusExp;//총 경험치 업데이트
저희 경험치 지급 로직은 다음과 같습니다.

커밋 1회: 5
데일리 보너스 경험치: 100
보너스 경험치 증가량: 10 (연속적으로 커밋하는 날이 늘어나면 증가)

이게 맞춰서 수정 부탁드립니다.

2024-07-20 16:57 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            LocalDateTime commitDate=commit.getCommitDate().toLocalDate().atStartOfDay();//커밋날짜를 가져와 시간 설정
`commitDate`의 자료형이 `LocalDateTime`이기 때문에 `getCommitDate()` 메서드만 있어도 정상적으로 실행이 될 것 같습니다.

2024-07-20 16:59 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        user.setExp(totalExp);//사용자 경험치 업데이트
위에서 말씀드린 것과 마찬가지로 `updateExp`와 같이 변경하는 의도가 명확하도록 이름을 변경하면 가독성이 더 좋을 것 같습니다.

2024-07-20 16:59 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        user.setExp(totalExp);//사용자 경험치 업데이트
위에서 말씀드린 것과 마찬가지로 updateExp와 같이 변경하는 의도가 명확하도록 이름을 변경하면 가독성이 더 좋을 것 같습니다.

2024-07-20 17:08 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<List<UserResponse>> searchUsers(@RequestParam("githubId") String githubId){//유저 이름으로 검색하는 앤드포인트
API 주소는 아래와 같이 변동되는 값으로도 API를 지정할 수 있는데 어떻게 생각하시나요?
```java
@GetMapping("/{githubId}")
public ApiResponse<List<UserResponse>> searchUsers(@PathVariable String githubId) {
```

2024-07-20 17:12 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +        return ApiResponse.onSuccess(users);//검색 결과 반환
아래와 같이 코드를 수정하면 가독성이 더 좋고 불필요한 선언을 줄일 수 있습니다!
```java
return ApiResponse.onSuccess(userQueryService.searchUsersByGithubId(githubId));
```

2024-07-20 17:13 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +        return ApiResponse.onSuccess(users);
여기도 마찬가지로 불필요한 선언을 줄일 수 있습니다.

2024-07-20 17:15 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<Page<UserRankResponse>> getUsersByExp(@PageableDefault(size = 50,sort = "exp",direction = Sort.Direction.DESC)
해당 API URL은 해당 기능의 의도를 파악하기 어렵습니다 `/ranking`과 같이 의도가 명확한 URL를 사용하면 좋을 것 같습니다.

2024-07-20 17:20 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/dto/response/UserResponse.java
> +) {
Figma를 보면 해당 페이지에 보여줘야 할 정보가 더 있습니다. Figma를 참고 하셔서 추가하면 좋을 것 같습니다.

2024-07-20 17:22 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        }
해당 코드는 `Optional<User>`를 사용하면 좀 더 간결하게 동일한 기능을 구현할 수 있을 것 같습니다.

2024-07-20 17:26 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +                .collect(Collectors.toList());//검색 결과를 UserResponse 객체로 변환하여 리스트 변환
`Optional<User>`를 활용하면 단일 `User` 객체를 얻어올 수 있기 때문에 더 간결하게 구현이 가능할 것입니다.

2024-07-20 17:27 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +                    user.getExp());
이 부분 또한 해당 페이지에 보여줘야 할 정보가 더 있습니다. Figma를 참고하셔서 추가하면 좋을 것 같습니다.

2024-07-20 17:28 UTC, yechan-kim commented
고생 많으셨습니다. 의견을 남겨두었으니 확인 부탁드립니다!

2024-07-21 08:20 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    private boolean isCalculated;//경험치 계산 여부를 나타낸다.
확인했습니다!! updateCnt에 this.isCalculated=false를 추가하였습니다.

2024-07-21 09:10 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            totalExp+=1+bonusExp;//총 경험치 업데이트
커밋 1회당 5가 지급이 되는건가요? 아니면 커밋 1일 당 5가 지급이 되는건가요?
그리고 데일리 보너스 경험치랑 보너스 경험치의 경우 연속 커밋 일수가 1이면 100, 2이면 110, 3이면 120 이런식으로 지급이 된다고 생각하면 되나요?

2024-07-21 09:16 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        user.setExp(totalExp);//사용자 경험치 업데이트
이 부분은 User에서 @Setter를 통해 사용되는 메서드라서 updateExp이런식으로 변경하려면 메서드를 추가해야할 것 같은데 그 부분이 더 좋을까요?

2024-07-21 09:21 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
>  }
변경하였습니다!!

2024-07-21 09:21 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        commits.sort(Comparator.comparing(Commit::getCommitDate));//오름차순으로 정렬
CommitRepository에 메서드를 추가하고 ExpService를 수정하였습니다.

2024-07-21 09:21 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            LocalDateTime commitDate=commit.getCommitDate().toLocalDate().atStartOfDay();//커밋날짜를 가져와 시간 설정
아 그렇네요!! 수정했습니다.

2024-07-21 09:24 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            totalExp+=1+bonusExp;//총 경험치 업데이트
기본적으로 커밋 1회당 5의 경험치를 지급합니다. 나머지 내용은 생각하신 내용과 동일합니다!

2024-07-21 09:30 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<List<UserResponse>> searchUsers(@RequestParam("githubId") String githubId){//유저 이름으로 검색하는 앤드포인트
혹시 저렇게 변경하면 어떤 부분이 좋아지거나 달라지는지 알 수 있을까요?

2024-07-21 09:32 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        user.setExp(totalExp);//사용자 경험치 업데이트
개인 차이라고 생각하긴 하는데, 저는 말씀드린 이유로 `@Setter` 사용을 지양하는 편입니다.
이 [글](https://hstory0208.tistory.com/entry/JPA-Entitiy%EC%97%90%EC%84%9C-%EC%99%9C-Setter%EB%A5%BC-%EC%82%AC%EC%9A%A9%ED%95%98%EC%A7%80-%EB%A7%90%EB%9D%BC%EA%B3%A0-%ED%95%A0%EA%B9%8C)을 한번 읽어 보시면 해결하는데 도움이 될 것 같습니다!

2024-07-21 09:37 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +        return ApiResponse.onSuccess(users);//검색 결과 반환
아 그렇네요!! 수정했습니다.

2024-07-21 09:38 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +        return ApiResponse.onSuccess(users);
수정했습니다!!

2024-07-21 09:38 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<Page<UserRankResponse>> getUsersByExp(@PageableDefault(size = 50,sort = "exp",direction = Sort.Direction.DESC)
확인하고 수정했습니다!!

2024-07-21 09:47 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<List<UserResponse>> searchUsers(@RequestParam("githubId") String githubId){//유저 이름으로 검색하는 앤드포인트
기존 코드의 API 예시 URI: `~/search?githubId=1winhyun`
제안한 코드의 API 예시 URI: `~/1winhyun`

변경되는 점은 이렇습니다. 저도 해당 내용을 찾아봤는데 CRUD를 하지 않는 한 위의 코드를 많이 사용하는 것 같습니다.
이게 더 좋다는 점은 따로 없어서, 이상 없으면 변경을 하지 않아도 될 것 같습니다.

2024-07-21 11:53 UTC, leejuae requested changes
수고하셨습니다!! 👏 👏 (이건 스타일 차이가 좀 심한거같긴 하지만,,) 주석덕에 보기 편했어요

2024-07-21 11:53 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    }
**티어테이블에 티어 정보가 다 저장되어있고, 해당 티어로 유저 정보에 저장되는 형식** 아니었나요??

티어를 새로 생성하는 것이 아닌, 해당하는 티어의 아이디를 유저 정보에 저장하는 것이 좋을거 같습니다 🙌
혹시나 티어가 없는 경우를 대비해 핸들링을하고 싶으신거라면 그냥 티어가 존재하지 않는다는 에러메시지를 띄우는게 좋을거같아요!

2024-07-21 11:53 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
>      private Integer exp;
이렇게 설정해도 되지만, 해당 방식은 데이터베이스에 의존하는 방식이라 JPA에서는 선호하지 않는 방식입니다!
종종 비슷한 형태를 보신 적이 있을 것 같은데 

```java
    @Column(nullable = false)
    private int yourField;

    public User() {
        this.yourField = 0;
    }
```

이렇게 설정해두시면, 엔티티 생성과 동시에 기본값이 0으로 초기화되어 데이터베이스에 입력되게 됩니다!

2024-07-21 12:54 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +            totalExp+=1+bonusExp;//총 경험치 업데이트
넵!! 수정했습니다!!

2024-07-22 04:00 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        }
간결하게 수정했습니다!!
```java
User user=userRepository.findByGithubId(githubId)
                .orElseThrow(()->new ApiException(ErrorStatus._USER_NOT_FOUND));
```

2024-07-22 04:00 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +                .collect(Collectors.toList());//검색 결과를 UserResponse 객체로 변환하여 리스트 변환
간결하게 수정했습니다!!
```java
expService.calculateAndSaveExp(user.getGithubId());
        return List.of(new UserResponse(
                user.getUsername(),
                user.getExp()!=null?user.getExp():0,
                user.getTier()!=null?user.getTier().getTierName():"Unranked"
        ));
```

2024-07-22 12:51 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        return List.of(new UserResponse(
리스트로 반환을 받는 이유가 있을까요?

2024-07-22 13:29 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +                    user.getExp());
티어와 연속 커밋 일수를 추가하였습니다!!

2024-07-22 13:29 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/dto/response/UserResponse.java
> +) {
연속 커밋일수를 추가하였습니다!!

2024-07-22 13:36 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        return List.of(new UserResponse(
아 원래는 username으로 검색을 진행하려 했는데 이와 같은 경우 여러명의 사용자가 나올 수도 있지 않을까 생각해서 리스트로 받으려는 생각을 처음에 했었습니다. 그런데 githubId도 검색하는 것으로 변경하고 나서는 한명의 사용자만 나올 것 같습니다. 즉, 크게 의미가 없어진 것 같습니다. List를 빼는게 좋을까요??

2024-07-22 14:51 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        return List.of(new UserResponse(
해당 로직을 보면 사용자는 한 명만 나올 것 같아서 리스트로 반환할 필요는 없을 것 같습니다.

2024-07-22 16:38 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    }
어떤 형식으로 해야하는지 아직 잘 모르겠는데 조금만 더 자세하게 알려주실 수 있나요?

2024-07-22 16:47 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        return List.of(new UserResponse(
리스트 반환 삭제하였습니다!!

2024-07-23 14:06 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +        user.setExp(totalExp);//사용자 경험치 업데이트
@Setter 삭제 후 메서드를 추가했습니다!!

2024-07-23 16:33 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    }
주애님 말씀해주신대로 수정은 했는데 맞는지 확실하지가 않아서 한번 확인부탁드리겠습니다!!

2024-07-24 00:54 UTC, leejuae requested changes

2024-07-24 00:54 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
> +    private String refreshToken;
이부분 삭제 부탁드릴게요!! 충돌 병합 과정에서 살리신거 같은데 리프레쉬 토큰은 저장 안하는걸로 바뀌었습니다!

2024-07-24 00:54 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
> +    private int yourField;
혹시 이거 어떤 컬럼일까요...? 이름만으로는 유추가 조금 어려워서 좀 더 확실한 이름으로 바꿔주시면 좋을 것 같아요!

2024-07-24 00:58 UTC, leejuae requested changes

2024-07-24 00:58 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
제가 생각한 방식은 findByTierId({id})같은걸 통해 가져오는걸 생각한거에요,,! 이렇게 처리해도 될거 같긴 한데,, 테스트시 잘 동작 했나요??

2024-07-24 05:50 UTC, yechan-kim commented
고생하셨습니다. 의견을 남겨두었으니 확인 부탁드립니다.

2024-07-24 05:53 UTC, yechan-kim requested changes
고생하셨습니다. 의견을 남겨두었으니 확인 부탁드립니다.

2024-07-24 05:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    public void isCommitCalculated(boolean calculated){isCalculated=calculated;}//isCalculated 필드 설정
해당 메서드의 의도를 보니 `commit`의 상태를 업데이트하기 위한 것으로 보입니다. 의도 파악이 쉽도록 메서드명을 변경하면 코드의 가독성이 더 좋아질 것 같습니다.

2024-07-24 05:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/dto/response/UserSearchResponse.java
> +public record UserSearchResponse(
Figma를 보시면, 오늘 커밋 횟수, 총 커밋 횟수를 표현을 해줘야 하는데, 해당 내용이 빠져 있습니다. DTO에 해당 내용도 추가해 주시기 바랍니다.

2024-07-24 05:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +            throw new ApiException(_USER_NOT_FOUND);
여기 때문에 `_USER_NOT_FOUND`를 `static`으로 `import` 한 것 같은데, 37번째 줄처럼 `ErrorStatus._USER_NOT_FOUND`으로 호출하는 것이 어떤 의도로 상수를 호출했는지 알 수 있어 가독성이 더 좋다고 생각합니다!

2024-07-24 05:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
`user`가 `null`일 수 있으니, 예외 처리를 통해서 `null`을 가져오지 못하도록 하는 게 좋을 것 같습니다.

2024-07-24 05:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
아까 말했던 것처럼 예외 처리를 해 주시면 `get()`메서드를 사용하지 않아도 됩니다.

2024-07-24 16:32 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
> +    private int yourField;
이 부분은 잘못 만들었습니다. 리뷰를 잘못 읽고 잘못 수정한 부분이라 삭제한 부분입니다. 원래 구현하려던 부분은 exp 기본값 0으로 설정하는 것이고 수정하였습니다.

2024-07-24 16:32 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
> +    private String refreshToken;
삭제했습니다!!

2024-07-24 16:34 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +            throw new ApiException(_USER_NOT_FOUND);
이 부분은 제가 작성한 부분이 아니긴 하지만 수정하였습니다!!

2024-07-24 18:04 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    public void isCommitCalculated(boolean calculated){isCalculated=calculated;}//isCalculated 필드 설정
commit 상태를 업데이트를 위함이라 저렇게 메서드명을 설정한건데 혹시 어떤식으로 해야 더 의도 파악이 쉬운 느낌일까요...?

2024-07-24 18:18 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
이 부분도 제가 작성한 부분이 아니긴 하지만
```java
if(user == null){
            throw new ApiException(ErrorStatus._USER_NOT_FOUND);
        }
``` 
이 부분을 통해 이미 예외 처리를 한게 아닌가요?

2024-07-24 18:19 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
이 부분도 제가 작성한 부분이 아닌데 어떤 뜻은지 잘 이해가 가지 않아서 수정을 못했습니다!!

2024-07-24 18:42 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
테스트 실행에서는 nullPointerException이 나타나는데 코드를 살펴보면 두가지 가능성이 있다고 생각되었습니다. 1. 데이터베이스에 Tier테이블에 null값이 없다. 2. Tier엔티티의 requiredExp에 NOT NULL을 추가하지 않은 문제. 2번의 경우로 먼저 nullable=false를 선언하고 테스트를 진행하였는데 계속해서 똑같은 오류가 나타났습니다. 이러면 데이터베이스 문제인데 이를 어떻게 해야할지를 잘 모르겠습니다.

2024-07-25 01:00 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
음 아마 데이터베이스에 데이터 없어서 문제 발생한거 같아요! 추가해두었으니 확인 부탁드릴게요

2024-07-25 02:05 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/presentation/dto/response/UserSearchResponse.java
> +public record UserSearchResponse(
추가하였습니다

2024-07-25 04:34 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    public void isCommitCalculated(boolean calculated){isCalculated=calculated;}//isCalculated 필드 설정
`isCommitCalculated`는 상태를 변경한다는 의미보다는, 지금 상태를 묻는 느낌이 더 강하다고 생각합니다. 
`toCalculated`이나, `updateStatustoCalculated`가 좋은 예시가 될 것 같습니다.
참고로 메서드명은 동사 또는 전치사로 시작하는 것이 바람직하니 참고하면 좋을 것 같습니다!

2024-07-25 04:48 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
앞서 말한 부분까지 합쳐서,
```java
User user = userRepository.findByGithubId(githubId).orElseThrow(() -> new ApiException(_USER_NOT_FOUND));
```
으로 합칠 수 있기 때문에 말씀드렸습니다! 해당 커밋은 @leejuae 님이 작성하신 내용으로 파악되어 다른 이유가 없으면 해당 코드로 수정하는 것이 좋을 것 같습니다!

2024-07-25 04:49 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
@leejuae 님 의견 들어보고 수정하는 방향으로 갈게요!

2024-07-25 06:42 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/domain/Commit.java
> +    public void isCommitCalculated(boolean calculated){isCalculated=calculated;}//isCalculated 필드 설정
수정하였습니다!!

2024-07-25 07:40 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
바꿔도 될거같아요!

2024-07-25 07:41 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
동일합니다!

2024-07-25 07:43 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
승현님 혹시 로컬 디비로 연결되어있지 않나요..? 그럼 로컬에서 데이터 직접 추가하고 테스트 해봐야될거같아서

```sql
INSERT INTO commitato.tier (required_exp, created_at, updated_at, tier_id, badge_url, character_url, tier_name) VALUES (0, '2024-07-25 09:56:08.000000', '2024-07-25 09:58:19.000000', 0xEFBBBF62353164656630302D35643430, 'default.png', 'default.png', '바보 감자');
INSERT INTO commitato.tier (required_exp, created_at, updated_at, tier_id, badge_url, character_url, tier_name) VALUES (1000, '2024-07-25 09:58:15.000000', '2024-07-25 09:58:21.000000', 0xEFBBBF00000000000000000000000000, 'default.png', 'default.png', '말하는 감자');
INSERT INTO commitato.tier (required_exp, created_at, updated_at, tier_id, badge_url, character_url, tier_name) VALUES (15000, '2024-07-25 09:58:16.000000', '2024-07-25 09:58:22.000000', 0xEFBBBF33000000000000000000000000, 'default.png', 'default.png', '개발자 감자');
INSERT INTO commitato.tier (required_exp, created_at, updated_at, tier_id, badge_url, character_url, tier_name) VALUES (33000, '2024-07-25 09:58:18.000000', '2024-07-25 09:58:24.000000', 0xEFBBBF34000000000000000000000000, 'default.png', 'default.png', 'CEO 감자');
```
이 데이터로 한번 테스트해보시겠어요?

2024-07-25 12:29 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
![image](https://github.com/user-attachments/assets/0e4f6af5-0704-44f5-9257-c43a667785c3)
데이터 추가하고 진행하니 nullPointerException 오류가 나지 않습니다!!

2024-07-25 12:31 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +                .orElseThrow(()->new RuntimeException("해당 경험치의 티어가 없음"+exp));
오 다행이에요!!! 다른것도 수정 하고, 예찬님도 오케이 하시면 머지해도 좋을거같아요! 너무 수고하셨어요 👍👍👍

2024-07-25 13:26 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
수정하였습니다!!

2024-07-25 13:26 UTC, 1winhyun commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +
수정하였습니다!

2024-07-25 14:05 UTC, yechan-kim approved these changes

2024-07-25 14:12 UTC, merged