19 fearture Tier 객채 생성
Leets-Official/Commitato-BE pull request #20
Opened 2024-07-25 19:17 UTC by yechan-kim

## 📌 요약
-  `Tier`객체들을 DB에 올리는 API를 개발하고, 사소한 버그들을 수정하였습니다.

## 📝 상세 내용
- `Tier`의 이미지를 S3 버킷에 업로드하고, `Tier` 객체들의 정보 `User`에 정상적으로 저장할 수 있는 로직을 구현했습니다.
  <img width="738" alt="image" src="https://github.com/user-attachments/assets/15f708aa-6af5-414f-ab4a-ebb8372a1f7a">

- `Tier`에 대한 내용은 사전에 DB에 넣을 예정이지만 테스트의 편의성을 위해 API로 집어 넣을 수 있도록 하였습니다.
  <img width="300" alt="image" src="https://github.com/user-attachments/assets/e20e61cc-fb4c-4bdb-a91d-92bfd5fd6226">

- 요구사항 변경으로 인해, `User`에서 `badge`칼럼을 삭제하였습니다.
- 검색하거나 랭킹 정보를 불러올 때 경험치 계산을 한 번 더 해서 연속 커밋 일수와, 커밋 날짜가 정상적으로 출력되지 않는 현상을 수정했습니다.
- `Tier`객체가 미 구현되어 임시로 구현한, 예외 처리 로직을 변경하였습니다.
- 기존에 GitHub Access Token을 불러오지 못하는 현상이 해결되어, `FetchCommit`의 테스트 로직을 수정하였습니다.
  <img width="457" alt="image" src="https://github.com/user-attachments/assets/94679a71-1861-4c88-8f62-725bbedb2ac8">
  <img width="515" alt="image" src="https://github.com/user-attachments/assets/91280fee-fc52-4e1a-8c62-4847a04998e4">

- Ec2에서 CORS가 차단되어 있는 문제를 해결하였습니다.
- CodeDeploy에서 배포 후 `after-deploy.sh`를 실행하지 못하는 버그를 수정했습니다.
- Ec2에서 스프링의 실행 로그를 볼 수 있도록 수정하였습니다.
- Ec2에서 더미 데이터를 쌓기 위해 DB 저장 전략을 `update`로 변경하였습니다.

## 🗣️ 질문 및 이외 사항
- `page`에 대해서 잘 몰라서 그러는데, 페이지 번호만 넘겨주면 랭킹 페이지를 불러올 수 있게끔 변경하면 더 좋을 것 같은데 의견 주시면 감사하겠습니다.
  <img width="276" alt="image" src="https://github.com/user-attachments/assets/6876267c-622d-4c3a-9f51-e02c7611fbc5">
- 간단히 말해 위의 `DTO` 대신에 페이지 번호만 넣으면 랭킹 정보를 출력할 수 있는지 궁금합니다.

## ☑️ 이슈 번호
- close #19

2024-07-26 02:51 UTC, leejuae requested changes
수고하셨습니다! 코드 관련하여 전 따로 리뷰는 없고 페이지네이션에 관해 제 의견을 드리자면,

페이징은 DTO형태가 아니라, 쿼리 파라미터 형태로 보내주는 것이 좋다고 생각합니다!

GET `/rank/pages?page=0&size=10`

RESPONSE
 ```json
{
  "isSuccess": true,
  "code": "COMMON200",
  "message": "성공입니다.",
  "result": {
	 "content": [...]
	 "customPage": {
	    "totalElements": "Long"
	    "totalPage": "Integer",
	    "currPage": "Integer",
	    "isFirst": "boolean",
	    "isLast": "boolean",
	    "hasNext": "boolean"}
}
```
이러한 형태로 리턴해주면 프론트측에서도 사용하기 편하다고 해서 이렇게 구현했었어요!
customPage는 프론트분 의견대로 수정해서 만든 DTO입니다.
혹시 구현 함수 원하시면 보내드릴게요!
[참고링크](https://devlog-wjdrbs96.tistory.com/414)

2024-07-26 05:04 UTC, yechan-kim commented
자료 감사합니다! 자료를 읽어봤으나, 잘 구현이 되어있는 것 같아서 어디를 수정해야할지 아직 감이 안 잡하네요... 혹시 예제 코드를 받아볼 수 있을까요?

2024-07-26 05:21 UTC, leejuae commented
@yechan-kim 제 코드를 정답이라고 할 순 없지만,, 참고 해주세요!

## 컨트롤러
```java
@GetMapping("/users/pages")
public ApiResponse<CustomPage<UserStickerItems>> getSpecificUserStickersPage(HttpServletRequest request,
                                                                                 @RequestParam(name = "page") int page,
                                                                                 @RequestParam(name = "size") int size) {
      Long userId = jwtProvider.getUserIdFromToken(request);
      return ApiResponse.onSuccess(userStickerQueryService.getPageStickersByUserId(userId, page, size));
}
```
## 서비스
```java
public CustomPage<UserStickerResponse.UserStickerItems> getPageStickersByUserId(Long userId, int page, int size) {
        Pageable pageable = PageRequest.of(page, size);
        Page<UserSticker> userStickerPage = userStickerRepository.findByUserId(userId, pageable);

        if (userStickerPage.isEmpty()) {
            return new CustomPage<>(Page.empty(pageable));  // 빈 페이지 반환
        }

        List<Long> stickerIds = userStickerPage.stream()
                .map(UserSticker::getStickerId)
                .collect(Collectors.toList());

        List<StickerResponse.StickerItem> stickerItems = stickerIds.stream()
                .map(stickerQueryService::getStickerById)
                .collect(Collectors.toList());

        UserStickerResponse.UserStickerItems userStickerItems = UserStickerResponse.toUserStickerItems(userId, stickerItems);

        List<UserStickerResponse.UserStickerItems> userStickerItemsList = List.of(userStickerItems);

        return new CustomPage<>(new PageImpl<>(userStickerItemsList, pageable, userStickerPage.getTotalElements()));
}
```

## 커스텀 페이징 클래스
```java
public class CustomPage<T> {
    private List<T> content; // 응답 DTO 내용!
    private boolean isFirst; // 첫번째 페이지인지 여부
    private boolean isLast; // 마지막 페이지인지 여부
    private int totalPage; // 전체 페이지 개수
    private long totalElements; // 전체 응답리스트의 요소 개수
    private int size; // 페이지 한번에 담아 보내는 요소의 크기
    private int currPage; // 현재 페이지 번호
    private boolean hasNext; // 다음페이지가 남아 있는지 여부

    public CustomPage(Page<T> page) {
        this.content = page.getContent();
        this.isFirst = page.isFirst();
        this.isLast = page.isLast();
        this.totalPage = page.getTotalPages();
        this.totalElements = page.getTotalElements();
        this.size = page.getSize();
        this.currPage = page.getNumber();
        this.hasNext = page.hasNext();
    }

    @JsonProperty("content")
    public List<T> getContent() {
        return content;
    }

    @JsonProperty("isFirst")
    public boolean isFirst() {
        return isFirst;
    }

    @JsonProperty("isLast")
    public boolean isLast() {
        return isLast;
    }

    @JsonProperty("totalPage")
    public int getTotalPage() {
        return totalPage;
    }

    @JsonProperty("totalElements")
    public long getTotalElements() {
        return totalElements;
    }

    @JsonProperty("size")
    public int getSize() {
        return size;
    }

    @JsonProperty("currPage")
    public int getCurrPage() {
        return currPage;
    }

    @JsonProperty("hasNext")
    public boolean isHasNext() {
        return hasNext;
    }
}
```

저는 이런 형식으로 짰었어요!

2024-07-26 06:49 UTC, yechan-kim commented
<img width="359" alt="image" src="https://github.com/user-attachments/assets/a347948b-b942-4df4-9742-873810bd3f72">
이런 식으로 나오면 정상적으로 나오는 건가요?
코드도 새로 작성했으니 확인 부탁드립니다!

2024-07-26 08:28 UTC, leejuae requested changes
맞습니다👍👍 받아오는 방식은 그렇게 하는게 좋을거같고, size만 리뷰 달아드린 형태로 바꾸는게 좋을거같아요!

2024-07-26 08:28 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<CustomPage<UserRankResponse>> getUsersByExp(@RequestParam(name = "page") int page) {
프론트분들이 받아올 사이즈도 정하는게 좋을거 같아서 쿼리 파라미터로 사이즈도 같이 받는게 좋을거 같아요!

2024-07-26 08:28 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, 50);
여기도 동일하게 50으로 지정하는게 아니라 변수로 지정해주는게 좋을 것 같습니다!

2024-07-26 08:30 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/presentation/UserController.java
> +    public ApiResponse<CustomPage<UserRankResponse>> getUsersByExp(@RequestParam(name = "page") int page) {
넵 알겠습니다. 변경하도록 하겠습니다.

2024-07-26 08:33 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        Pageable pageable = PageRequest.of(page, 50);
수정하였습니다!

2024-07-26 12:51 UTC, ay-eonii reviewed
안녕하세요 예찬!

최종 발표가 코앞이라 고생 많네요 ㅎㅎ
간단히 리뷰 몇 가지 남겼으니 확인 부탁드려요~ 필수 반영하지 않아도 되고, 팀원들 간 상의하거나 예찬님의 판단 하에 조정해도 좋습니다.

1. 전반적으로 EOF 경고가 발생하는 지점이 많이 보여요. intelliJ 에서 설정도 가능하니 알아보심 좋을 듯 해요 ㅎㅎ
2. 거의 모든 코드에 주석이 달려있네요. 주석이 없으면 코드를 이해하기 어렵다는 뜻이겠죠? 그렇다면 어떻게 해야 이해하기 쉬운 코드를 작성할 수 있는지 고민해봐도 좋을 것 같아요. 메서드명을 잘 이용한다거나, 객체에게 책임을 맡기는 방법도 있겠네요.

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        }
티어가 없으면 유저의 어떤 정보도 볼 수 없도록 설계한 상황이 맞나요?
보통 서비스에서는 없는 정보는 빈칸이나 없다고 알려주고 있는 정보만이라도 보여주던 것 같아서요!

이 부분은 기획적인 측면이라 단순 질문입니다!

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +            }
인덴트 확인해주세요~

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    public void calculateAndSaveExp(String githubId) {
중간중간 Commit 객체의 책임으로 둘 만한 로직도 있는 것 같아요. 그렇게 된다면 코드가 더 클린해질 것 같아요~!

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/FetchCommitsTest.java
> +}
<img width="97" alt="image" src="https://github.com/user-attachments/assets/35fd988f-91aa-40c9-9b0a-b7fd77388fc9">

EOF 경고가 발생하고 있어요~

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/tier/presentation/TierController.java
> +
팀 내에서 개행에 대한 컨벤션이 있나요? 없다면 정해보는 것도 좋을 것 같아요. 사소해보이지만 다른 사람입장에서는 가독성이 떨어지고 나아가 어떤 의미가 있는지 고민하는 포인트가 될 수도 있어요~

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/tier/presentation/dto/request/TierRequest.java
> +public record TierRequest() {
이 record는 무엇을 하고있나요?

2024-07-26 12:51 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/tier/usecase/CreateInitialTiers.java
> +public class CreateInitialTiers {
테스트를 위해 초기 데이터를 넣는 작업이라면 `data.sql`을 이용해볼 수 있을 것 같아요~
[참고](https://wildeveloperetrain.tistory.com/228)

2024-07-26 12:54 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/global/shared/CustomPage.java
> +    }
다른 DTO는 record를 사용하는데 이 클래스에 대해서는 `@Getter`나 record를 사용하지 않고 하나하나 메서드를 생성한 이유가 있나요?

2024-07-26 12:55 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +            }
오 이 부분은 아니네요 ㅎㅎ 착각했어요 😅

2024-07-26 14:07 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/usecase/UserQueryServiceImpl.java
> +        }
원래는 그런 로직으로 작성이 되어있었습니다. 하지만, 기본적으로 `Tier`는 DB에 모든 정보를 사전에 주입하기 때문에 API 상 오류가 아니라면,  `Tier`가 `null`이 될 수 없기에 대체 값을 보여주는 것보다, 예외 처리를 하는 것이 더 좋다고 판단하여 로직을 변경했었습니다. 코드를 다시 확인해 보니, `Tier`를 생성하거나 업데이트할 때, `null`값에 대한 예외 처리가 이미 되어 있어서 추가적인 예외 처리는 필요 없다고 판단이 됩니다. 따라서, 해당 예외 처리는 삭제하는 게 맞는다고 생각합니다. 지금은 삭제하고 추후에 리팩토링할 때 이 부분에 대해서 팀원들과 이야기를 다시 한번 나눠보겠습니다.

2024-07-26 14:53 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/FetchCommitsTest.java
> +}
EOF 경고가 발생하는 부분은 전부다 수정 완료하였습니다!

2024-07-26 14:56 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/tier/presentation/TierController.java
> +
해당 사항은 회의를 통해서 결정하도록 하겠습니다!

2024-07-26 14:59 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/tier/presentation/dto/request/TierRequest.java
> +public record TierRequest() {
구조를 쉽게 파악하기 위해 만들어둔 DTO입니다. 사용하지 않으면, 리펙터링 때 삭제할 예정입니다.

2024-07-26 15:54 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    public void calculateAndSaveExp(String githubId) {
코드를 읽어봤으나, 커밋 횟수로 인해 지급되는 경험치를 반환하는 로직 말고는 발견하지 못했습니다. 혹시 다른 로직이 있으면 알려주실 수 있을까요?

2024-07-26 15:58 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/global/shared/CustomPage.java
> +    }
`Page`라는 타입을 커스텀을 한 것으로 판단했기 때문에, `record`가 아닌 `class`로 구현하는 것이 옳다고 판단했습니다. 해당 객체는 `DTO`라고 보는 것이 맞을까요?

2024-07-26 16:37 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/tier/usecase/CreateInitialTiers.java
> +public class CreateInitialTiers {
좋은 의견 감사합니다. 티어 생성 로직을 `data.sql`을 이용하는 로직으로 변경하였습니다!

2024-07-27 05:08 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/global/shared/CustomPage.java
> +    }
팀원분들과 의논해 봤는데, `DTO`로 반환하는 것이 옳다고 판단해 `DTO`로 변경하였습니다. 의견 감사합니다!

2024-07-29 02:34 UTC, leejuae approved these changes
고생하셨습니다! 👍👍

2024-07-29 10:31 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    public void calculateAndSaveExp(String githubId) {
저는 commit의 get으로 내부 속성을 꺼내오는 것 (대부분 모두) 내부에서 처리할 수 있을 것으로 보여요. 

대표적으로 `if (commitDate.toLocalDate().isEqual(LocalDate.now())) `이 있을 것 같아요

2024-07-29 10:34 UTC, ay-eonii commented on src/main/java/com/leets/commitatobe/global/shared/CustomPage.java
> +    }
어떤 이유로 해당 객체를 DTO로 변경했는지 궁금해요

2024-07-29 10:47 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/commit/usecase/ExpService.java
> +    public void calculateAndSaveExp(String githubId) {
저도 그렇다고 판단하여, `Commit` 갹체 내부에서 처리가 가능하다고 판단된 로직들은 내부에서 처리하도록 변경하였습니다!

2024-07-29 10:50 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/global/shared/CustomPage.java
> +    }
처음에는 타입으로 생각하였으나, 응답 값을 전달해 준다는 목적 이외에는 다른 목적이 없다고 판단했습니다. 따라서 객체보다는 DTO의 성격이 강하다고 판단하였고, 다른 DTO와 같이 `record`로 변경하였습니다!

2024-07-29 14:28 UTC, merged