1 feature 로그인 로직 구현
Leets-Official/Commitato-BE pull request #3
Opened 2024-07-13 12:46 UTC by leejuae

## 📌 요약

- 깃허브 OAuth 로그인 구현

## 📝 상세 내용

- 깃허브를 통해 OAuth로 깃허브 사용자 정보 불러옴
- 불러온 정보로 jwt 생성

## 🗣️ 질문 및 이외 사항

member class를 만들어 깃허브 엑세스 토큰을 저장중입니다. 해당 엑세스 토큰으로 깃허브 정보에 접근하면 될 것 같습니다!

## ☑️ 이슈 번호

- close #1

2024-07-13 12:59 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +public class Member {
`User`를 사용하지 않고 `Member`를 사용한 이유가 있을까요?

2024-07-13 13:30 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/login/controller/LoginController.java
> +import com.leets.commitatobe.domain.login.Member;
사용하지 않는 `import`문은 삭제하면 좋을 것 같습니다.

2024-07-13 13:31 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/login/dto/GitHubDto.java
> +    public record GitHubResponse(
레코드를 클래스 내부에 구현하신 이유가 있을까요?

2024-07-13 13:38 UTC, jwnnoh requested changes
고생하셨습니다! 코멘트 확인 부탁드려요 👍

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +public class Member {
class 명은 `User`로 하되,
Entity 어노테이션을 통해 `Users` 방식으로 JPA 오류를 방지하면 좋을 것 같아요!

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String githubAccessToken; // 깃허브 액세스 토큰
깃허브 액세스 토큰을 왜 DB에 저장하는지 알 수 있을까요?

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String refreshToken; // 깃허브 리프레시 토큰
저장되는 리프레시토큰이 자체 생성 JWT 토큰인지, 깃허브 리프레시 토큰인지 궁금합니다!

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private List<String> roles = new ArrayList<>();
권한을 왜 List 형식으로 선언했는지 궁금합니다!

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/dto/GitHubDto.java
> +public class GitHubDto {
클래스 내에 내부 클래스로 레코드를 사용하기보다는, 레코드 클래스를 기반으로 하는 방식으로 DTO 클래스를 수정하면 좋을 것 같습니다 :)

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/dto/JwtDto.java
> +public class JwtDto {
마찬가지로, 클래스 타입을 record로 설정하시고, 기본 생성자를 통해 DTO를 생성해주면 좋을 것 같습니다 :)

2024-07-13 13:38 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/service/LoginService.java
> +        // 엑세스 토큰 쿠키
액세스토큰은 보안상의 이유로 쿠키에 담아서 전달하는 것을 추천드리지 않습니다..!
만약 쿠키를 사용하신다면 리프레시 토큰만 쿠키에,
그리고 나머지 값들은 DTO에 담아서 전달하는 것을 추천드려요 :)

2024-07-13 14:34 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +public class Member {
이부분 나중에 합칠때 충돌날까봐 Member로 해뒀어요! User로 합칠때 안에 있는 내용들 포함해서 넣으면 될거 같아요

2024-07-13 14:34 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String githubAccessToken; // 깃허브 액세스 토큰
아 이거 로직상 저장 안하는걸로 됐는데 아직 남아있었네요.. 삭제 해두겠습니다!

2024-07-13 14:38 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String refreshToken; // 깃허브 리프레시 토큰
자체 생성 jwt입니다!! 복붙하는 과정에서 코멘트까지 복붙해버렸네요 🥲 수정해두겠습니다

2024-07-13 14:49 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/dto/GitHubDto.java
> +    public record GitHubResponse(
클래스 외부 구현 방식으로 바꿨습니다!

2024-07-13 15:06 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/service/LoginService.java
> +        // 엑세스 토큰 쿠키
오 감사합니다! 안그래도 그 로직이 헷갈렸는데 좀 더 찾아보고 반영하겠습니다~!

2024-07-13 15:13 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private List<String> roles = new ArrayList<>();
여러 권한을 부여할 수 있다는 점에서 설정해뒀습니다! 다만,, 생각해보니 저희 서비스는 그정도까진 필요 없을 것 같아 스트링으로 수정하는게 좋을거같네요

2024-07-13 15:22 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String refreshToken; // 깃허브 리프레시 토큰
그렇다면 주석 내용 수정 부탁드립니다!

2024-07-13 15:27 UTC, jwnnoh requested changes
그리고 기능 구현이 완료되었다면, 스크린샷을 통한 기능의 동작 여부와 그에 따른 결과를 함께 보여주는 것도 무척 좋을 것 같습니다 :)

2024-07-13 17:13 UTC, jwnnoh requested changes
고생하셨습니다! 코멘트 확인 부탁드려요 😄

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/Member.java
> +    private String roles;
role이 한 개라면, 컬럼명도 roles가 아닌 role로 수정되어야 할 것 같아요!

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/dto/GitHubDto.java
내부 클래스를 통해서 얻는 이점을 찾기가 어려운 것 같아요..!!
하나의 클래스에 값들을 담아주는 것은 어떨까요?
```java
public record GitHubDto(String userId) {
}
```
또한, 전달 값이 하나라면 굳이 빌더를 사용할 이유는 없어보입니다!

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/dto/JwtDto.java
마찬가지로, 하나의 클래스를 정의해서 값들을 담아주는 방식이 더욱 좋아보입니다 :)

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
>      private String profileUrl;
컬럼마다 개행을 추가해주면 가독성이 높아질 것 같아요!
그리고, 컬럼명에 자료형을 쓰는 것은 추천드리지 않습니다!

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/user/domain/repository/UserRepository.java
>  @Repository
JPA는 기본적으로 제공되는 컴포넌트를 사용하기에,
어노테이션은 굳이 사용하지 않아도 무방합니다!

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/global/config/CustomOAuth2UserService.java
> +@Transactional
메서드와 클래스에 중복으로 `Transactional` 어노테이션을 다는 것은 추천드리지 않습니다..!!
클래스에 어노테이션을 달았다면, 메서드에도 중복되는 어노테이션을 달 필요는 없을 것 같습니다.

2024-07-13 17:13 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
>                                  .anyRequest().authenticated()
나머지 API를 `authenticated()`로 설정하셨는데,
시큐리티의 `AuthPrincipal` 객체를 통해 유저의 정보를 가져오는 클래스와 서비스 로직이 구현되어 있지 않는 것 같습니다!
헤더에서 토큰을 추출하여 유저를 인증하는 방식은 `authenticated()` 방식으로 접근이 제한된 API에 정상적으로 인증을 처리할 수 없어 요청이 불가능한 것으로 알고 있습니다 :)

2024-07-13 18:07 UTC, leejuae commented on src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
>                                  .anyRequest().authenticated()
혹시,, 이해가 잘 되지 않아서 그런데 관련 자료라도 공유해주실 수 있을까요?!

2024-07-13 19:34 UTC, MinhoJJang reviewed
수고하셨습니다!

2024-07-13 19:34 UTC, MinhoJJang commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
ManyToOne 혹은 OneToMany 설정 시 아래 포인트를 고려하면 좋을 듯 합니다. 데이터베이스 테이블 연관관계를 고려해보시고 필요하다 싶으시다면 사용해보시기 바랍니다. 
개인적으로 1번은 매 프로젝트마다 사용했던 것 같고, 2,3번은 경우에 따라 선택하는 편이었습니다. 

1. @JsonManagedReference, @JsonBackReference -> JSON 직렬화 무한루프를 방지(순환참조 방지)
2. CascadeType.ALL -> 부모의 변경사항을 자식에게 전파해야 하는 경우
3. orphanRemoval = true -> 부모가 삭제될 때 자식도 같이 삭제되어야 하는 경우

### 참고자료
[@JsonReferences](https://medium.com/@AlexanderObregon/understanding-springs-jsonbackreference-and-jsonmanagedreference-annotations-783090468572)
[CascadeType vs orphanRemoval](https://resilient-923.tistory.com/417)

2024-07-14 06:00 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
>                                  .anyRequest().authenticated()
```java
public interface Authentication extends Principal, Serializable {
    Collection<? extends GrantedAuthority> getAuthorities();

    Object getCredentials();

    Object getDetails();

    Object getPrincipal();

    boolean isAuthenticated();

    void setAuthenticated(boolean isAuthenticated) throws IllegalArgumentException;
}
```
해당  인터페이스는 아래 메서드가 스프링 시스템 내에서 유저의 인증 여부를 확인할 때 참고하는 정보인 `Authentication` 입니다.
```java
.anyRequest().authenticated()
```

하지만 현재 코드를 보면, 그러한 정보를 저장하는 `UserDetails` 인터페이스를 구현한 클래스가 없기에, 의도한 대로 인증하지 않은 유저의 api 요청 접근을 막을 수 없다는 점을 말씀드리는 겁니다! 😄 

```java
UserDetails
public interface UserDetails extends Serializable {
    Collection<? extends GrantedAuthority> getAuthorities();

    String getPassword();

    String getUsername();

    boolean isAccountNonExpired();

    boolean isAccountNonLocked();

    boolean isCredentialsNonExpired();

    boolean isEnabled();
}
```

따라서 추천드리는 방식은 다음과 같습니다.
1. User 엔티티 클래스에 UserDetails 인터페이스를 구현하는 방법
2. 별도의 UserDetails를 구현하는 클래스를 생성, 엔티티 클래스와의 책임을 분리

이를 통해 Spring Security에서 사용자의 정보를 불러올 수 있습니다 :)

자세한 내용은 아래 내용을 참고해주시면 더욱 이해가 잘 되실거라 믿습니다!
https://programmer93.tistory.com/68

2024-07-14 06:15 UTC, leejuae commented on src/main/java/com/leets/commitatobe/global/config/SecurityConfig.java
>                                  .anyRequest().authenticated()
오 자세한 설명 감사합니다!!

2024-07-14 12:16 UTC, leejuae commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
감사합니다~! ☺️ 리뷰 달아주셨네요

2024-07-14 17:58 UTC, jwnnoh reviewed
늦은 시간까지 고생하셨습니다! 코멘트 확인 부탁드려요..ㅎㅎ
파이팅!!

2024-07-14 17:58 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/domain/login/usecase/CustomUserDetailsService.java
> +    }
해당 방식보다는, `CustomUserDetails`에 변경이 자주 되지 않을 값들은 미리 저장해놓고 유저네임과 깃허브, 롤만 생성자로 생성하면 더욱 좋지 않을까요?
```java
return new CustomUserDetails(user.getUsername(), user.getGithubId(), Role.ROLE_USER);
```

```java
    private final 유저아이디;
    private final 깃허브아이디;
    private final Role role;

    @Override
    public Collection<? extends GrantedAuthority> getAuthorities() {
        return Collections.singletonList(new SimpleGrantedAuthority(role.getRole()));
    }

    @Override
    public String getPassword() {
        return null;
    }

    @Override
    public String getUsername() {
        return username;
    }

    @Override
    public boolean isAccountNonExpired() {
        return true;
    }

    @Override
    public boolean isAccountNonLocked() {
        return true;
    }

    @Override
    public boolean isCredentialsNonExpired() {
        return true;
    }

    @Override
    public boolean isEnabled() {
        return true;
    }
```

2024-07-14 17:58 UTC, jwnnoh commented on src/main/java/com/leets/commitatobe/global/config/CustomOAuth2UserService.java
> +
해당 인증 객체는 토큰의 claims에서의 정보를 기반으로 토큰을 관리하는 책임을 지니는 클래스에서 생성해주는 것을 추천드려요!
유저 생성 또는 로그인 시 해당 객체를 생성하지 않으셔도 됩니다 😄

2024-07-15 06:20 UTC, leejuae commented on src/main/java/com/leets/commitatobe/global/config/CustomOAuth2UserService.java
> +
알람이 안떠서 이제 확인했네요! ! 피드백 감사합니다 😊 수정해서 커밋했습니다!

2024-07-15 09:55 UTC, yechan-kim commented on build.gradle
> +    runtimeOnly 'com.mysql:mysql-connector-j' // MySQL 연결을 위한 Connector
해당 부분은 동일한 의존성이 파일 내부에 존재하고 있기 때문에 삭제를 권장합니다!

2024-07-15 10:28 UTC, yechan-kim commented on src/main/java/com/leets/commitatobe/domain/user/domain/User.java
사용하지 않은 패키지 같은데 추가한 이유가 있으실까요?

2024-07-15 13:47 UTC, merged